include(CheckCCompilerFlag)
include(CheckCXXCompilerFlag)
include(CheckCXXSourceCompiles)
include(CMakePushCheckState)

function(mars_titan_cxx_option flag)
    string(MAKE_C_IDENTIFIER "MARS_TITAN_CXX_${flag}" supported)
    check_cxx_compiler_flag("${flag}" ${supported})
    if(${supported})
        target_compile_options(mars_titan_native_options INTERFACE
            "$<$<COMPILE_LANGUAGE:CXX>:${flag}>")
    else()
        message(STATUS "Opción C++ no disponible: ${flag}")
    endif()
endfunction()

if(MSVC)
    foreach(flag /W4 /permissive- /sdl /Zc:__cplusplus /Zc:preprocessor /fp:strict)
        mars_titan_cxx_option("${flag}")
    endforeach()
    target_compile_options(mars_titan_native_options INTERFACE "$<$<COMPILE_LANGUAGE:C>:/W4>")
    if(MARS_TITAN_WARNINGS_AS_ERRORS)
        target_compile_options(mars_titan_native_options INTERFACE /WX)
    endif()
    if(MARS_TITAN_ENABLE_STATIC_ANALYZER)
        check_cxx_compiler_flag(/analyze MARS_TITAN_HAS_MSVC_ANALYZE)
        if(NOT MARS_TITAN_HAS_MSVC_ANALYZE)
            message(FATAL_ERROR "El compilador no admite el análisis /analyze solicitado")
        endif()
        target_compile_options(mars_titan_native_options INTERFACE /analyze)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    foreach(flag -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion -Wshadow
                 -Wformat=2 -Wnull-dereference -Wdouble-promotion -Wcast-align
                 -Wold-style-cast -Woverloaded-virtual -Wnon-virtual-dtor -Wimplicit-fallthrough)
        mars_titan_cxx_option("${flag}")
    endforeach()
    foreach(flag -Wall -Wextra -Wpedantic -Wconversion -Wshadow -Wformat=2 -Wnull-dereference)
        string(MAKE_C_IDENTIFIER "MARS_TITAN_C_${flag}" supported)
        check_c_compiler_flag("${flag}" ${supported})
        if(${supported})
            target_compile_options(mars_titan_native_options INTERFACE
                "$<$<COMPILE_LANGUAGE:C>:${flag}>")
        endif()
    endforeach()
    # La referencia numérica no admite reasociación ni contracción implícita.
    foreach(flag -fno-fast-math -ffp-contract=off)
        string(MAKE_C_IDENTIFIER "MARS_TITAN_PARITY_${flag}" supported)
        check_cxx_compiler_flag("${flag}" ${supported})
        if(NOT ${supported})
            message(FATAL_ERROR "El compilador no conserva la opción de paridad ${flag}")
        endif()
        target_compile_options(mars_titan_native_options INTERFACE
            "$<$<COMPILE_LANGUAGE:CXX>:${flag}>")
    endforeach()
    if(MARS_TITAN_WARNINGS_AS_ERRORS)
        target_compile_options(mars_titan_native_options INTERFACE -Werror)
    endif()
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        mars_titan_cxx_option(-Wdangling-pointer)
        mars_titan_cxx_option(-Wdangling-reference)
        if(MARS_TITAN_ENABLE_STATIC_ANALYZER)
            check_cxx_compiler_flag(-fanalyzer MARS_TITAN_HAS_GCC_ANALYZER)
            if(NOT MARS_TITAN_HAS_GCC_ANALYZER)
                message(FATAL_ERROR "GCC no admite -fanalyzer en esta configuración")
            endif()
            target_compile_options(mars_titan_native_options INTERFACE -fanalyzer)
        endif()
    elseif(MARS_TITAN_ENABLE_LIFETIME)
        check_cxx_compiler_flag(-Wlifetime-safety MARS_TITAN_HAS_LIFETIME_SAFETY)
        if(MARS_TITAN_HAS_LIFETIME_SAFETY)
            target_compile_options(mars_titan_native_options INTERFACE
                "$<$<COMPILE_LANGUAGE:CXX>:-Wlifetime-safety>")
        else()
            cmake_push_check_state(RESET)
            set(CMAKE_REQUIRED_FLAGS
                "-Werror=unknown-warning-option -Xclang -fexperimental-lifetime-safety -Wexperimental-lifetime-safety")
            check_cxx_source_compiles("int main() { return 0; }" MARS_TITAN_HAS_EXPERIMENTAL_LIFETIME)
            cmake_pop_check_state()
            if(MARS_TITAN_HAS_EXPERIMENTAL_LIFETIME)
                target_compile_options(mars_titan_native_options INTERFACE
                    "$<$<COMPILE_LANGUAGE:CXX>:-Xclang;-fexperimental-lifetime-safety;-Wexperimental-lifetime-safety>")
                message(STATUS "Lifetime Safety experimental activado")
            else()
                message(STATUS "Este Clang no ofrece un análisis de lifetime compatible")
            endif()
        endif()
    endif()
else()
    message(FATAL_ERROR "No hay un perfil de diagnóstico definido para este compilador")
endif()

check_cxx_source_compiles("#include <cstddef>\n#ifndef __GLIBCXX__\n#error Otra biblioteca\n#endif\nint main() { return 0; }"
    MARS_TITAN_USES_LIBSTDCXX)
if(MARS_TITAN_USES_LIBSTDCXX AND NOT MARS_TITAN_SANITIZER STREQUAL "memory")
    target_compile_definitions(mars_titan_native_options INTERFACE _GLIBCXX_ASSERTIONS=1)
else()
    cmake_push_check_state(RESET)
    set(CMAKE_REQUIRED_FLAGS "${MARS_TITAN_STDLIB_PROBE_FLAGS}")
    check_cxx_source_compiles("#include <cstddef>\n#if !defined(_LIBCPP_HARDENING_MODE_FAST) || !defined(_LIBCPP_HARDENING_MODE_EXTENSIVE)\n#error Sin hardening compatible\n#endif\nint main() { return 0; }"
        MARS_TITAN_HAS_LIBCPP_HARDENING)
    cmake_pop_check_state()
    if(MARS_TITAN_HAS_LIBCPP_HARDENING)
        target_compile_definitions(mars_titan_native_options INTERFACE
            "$<$<CONFIG:Release>:_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST>"
            "$<$<NOT:$<CONFIG:Release>>:_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE>")
    elseif(NOT MSVC)
        message(WARNING "No se detectó un modo de endurecimiento STL compatible")
    endif()
endif()

if(MARS_TITAN_ENABLE_CLANG_TIDY)
    string(REGEX MATCH "^[0-9]+" compiler_major "${CMAKE_CXX_COMPILER_VERSION}")
    find_program(MARS_TITAN_CLANG_TIDY NAMES "clang-tidy-${compiler_major}" clang-tidy REQUIRED)
    if(NOT EXISTS "${MARS_TITAN_CLANG_TIDY}")
        message(FATAL_ERROR "No existe el ejecutable clang-tidy solicitado")
    endif()
    execute_process(COMMAND "${MARS_TITAN_CLANG_TIDY}" --version
        RESULT_VARIABLE tidy_result OUTPUT_VARIABLE tidy_version ERROR_VARIABLE tidy_error)
    if(NOT tidy_result EQUAL 0)
        message(FATAL_ERROR "clang-tidy no se puede ejecutar: ${tidy_error}")
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND
       NOT tidy_version MATCHES "version ${compiler_major}\\.")
        message(FATAL_ERROR "clang-tidy debe compartir la versión principal de Clang")
    endif()
    message(STATUS "clang-tidy: ${MARS_TITAN_CLANG_TIDY}")
endif()

if(MARS_TITAN_ENABLE_STATIC_ANALYZER AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    string(REGEX MATCH "^[0-9]+" compiler_major "${CMAKE_CXX_COMPILER_VERSION}")
    find_program(MARS_TITAN_CLANG_CHECK NAMES "clang-check-${compiler_major}" clang-check REQUIRED)
    execute_process(COMMAND "${MARS_TITAN_CLANG_CHECK}" --version
        RESULT_VARIABLE analyzer_version_result OUTPUT_VARIABLE analyzer_version ERROR_VARIABLE analyzer_version_error)
    if(NOT analyzer_version_result EQUAL 0 OR NOT analyzer_version MATCHES "version ${compiler_major}\\.")
        message(FATAL_ERROR "clang-check necesita la versión principal de Clang: ${analyzer_version_error}")
    endif()
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/mars-analyzer-probe.cpp" "int main() { return 0; }\n")
    execute_process(COMMAND "${CMAKE_CXX_COMPILER}" --analyze -std=c++20
        -Xanalyzer -analyzer-output=text -Xanalyzer -analyzer-werror
        "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/mars-analyzer-probe.cpp"
        RESULT_VARIABLE analyzer_result ERROR_VARIABLE analyzer_error)
    if(NOT analyzer_result EQUAL 0)
        message(FATAL_ERROR "El analizador de rutas no admite las opciones requeridas: ${analyzer_error}")
    endif()
endif()
