include(CheckCXXSourceCompiles)
include(CMakePushCheckState)

if(NOT MARS_TITAN_SANITIZER MATCHES "^(none|address|address-undefined|thread|memory)$")
    message(FATAL_ERROR "La instrumentación solicitada no está soportada")
endif()
if(NOT MARS_TITAN_PGO MATCHES "^(off|generate|use)$")
    message(FATAL_ERROR "El modo PGO no está definido")
endif()
if(NOT MARS_TITAN_SANITIZER STREQUAL "none" AND
   (MARS_TITAN_PROFILE OR MARS_TITAN_ENABLE_CUDA OR MARS_TITAN_ENABLE_IPO OR NOT MARS_TITAN_PGO STREQUAL "off"))
    message(FATAL_ERROR "Separar sanitizadores CPU del perfil de rendimiento, CUDA, LTO y PGO")
endif()

if(MARS_TITAN_SANITIZER STREQUAL "memory")
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "MSan requiere Clang en Linux y dependencias instrumentadas")
    endif()
    if(NOT EXISTS "${MARS_TITAN_MSAN_STDLIB_ROOT}/include/c++/v1/cstddef")
        message(FATAL_ERROR "MSan necesita libc++ y libc++abi instrumentadas. Indica MARS_TITAN_MSAN_STDLIB_ROOT")
    endif()
    foreach(library c++ c++abi)
        string(MAKE_C_IDENTIFIER "MARS_TITAN_MSAN_${library}" variable)
        find_library(${variable} NAMES ${library}
            PATHS "${MARS_TITAN_MSAN_STDLIB_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
        execute_process(COMMAND "${CMAKE_NM}" --undefined-only "${${variable}}"
            OUTPUT_VARIABLE symbols ERROR_QUIET RESULT_VARIABLE nm_result)
        if(NOT symbols MATCHES "__msan_")
            execute_process(COMMAND "${CMAKE_NM}" --dynamic --undefined-only "${${variable}}"
                OUTPUT_VARIABLE symbols ERROR_QUIET RESULT_VARIABLE nm_result)
        endif()
        if(NOT nm_result EQUAL 0 OR NOT symbols MATCHES "__msan_")
            message(FATAL_ERROR "No se acredita instrumentación MSan en ${${variable}}")
        endif()
    endforeach()
    set(MARS_TITAN_STDLIB_PROBE_FLAGS
        "-fsanitize=memory -stdlib=libc++ -nostdinc++ -isystem \"${MARS_TITAN_MSAN_STDLIB_ROOT}/include/c++/v1\" -L\"${MARS_TITAN_MSAN_STDLIB_ROOT}/lib\"")
endif()

if(MARS_TITAN_ENABLE_IPO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT ipo_supported OUTPUT ipo_error LANGUAGES CXX)
    if(NOT ipo_supported)
        message(FATAL_ERROR "LTO no está disponible: ${ipo_error}")
    endif()
endif()

if(NOT MARS_TITAN_SANITIZER STREQUAL "none")
    if(MSVC)
        if(NOT MARS_TITAN_SANITIZER STREQUAL "address")
            message(FATAL_ERROR "MSVC admite este perfil con address. UBSan, TSan y MSan requieren otros perfiles")
        endif()
        set(MARS_TITAN_SANITIZER_FLAGS /fsanitize=address)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        if(MARS_TITAN_SANITIZER STREQUAL "address-undefined")
            set(MARS_TITAN_SANITIZER_FLAGS -fsanitize=address,undefined)
        else()
            set(MARS_TITAN_SANITIZER_FLAGS "-fsanitize=${MARS_TITAN_SANITIZER}")
        endif()
    else()
        message(FATAL_ERROR "El compilador no admite este perfil de sanitización")
    endif()
    cmake_push_check_state(RESET)
    string(JOIN " " CMAKE_REQUIRED_FLAGS ${MARS_TITAN_SANITIZER_FLAGS})
    set(CMAKE_REQUIRED_LINK_OPTIONS ${MARS_TITAN_SANITIZER_FLAGS})
    string(MAKE_C_IDENTIFIER "MARS_TITAN_HAS_SANITIZER_${MARS_TITAN_SANITIZER}" sanitizer_probe)
    check_cxx_source_compiles("int main() { return 0; }" ${sanitizer_probe})
    cmake_pop_check_state()
    if(NOT ${sanitizer_probe})
        message(FATAL_ERROR "No se pudo compilar y enlazar el runtime ${MARS_TITAN_SANITIZER}")
    endif()
endif()

if(MARS_TITAN_BUILD_FUZZER)
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR NOT MARS_TITAN_SANITIZER STREQUAL "address-undefined")
        message(FATAL_ERROR "El fuzzing requiere Clang y el perfil address-undefined separado")
    endif()
    cmake_push_check_state(RESET)
    set(CMAKE_REQUIRED_FLAGS "-fsanitize=fuzzer,address,undefined")
    check_cxx_source_compiles("#include <cstddef>\nextern \"C\" int LLVMFuzzerTestOneInput(const unsigned char*, std::size_t) { return 0; }"
        MARS_TITAN_HAS_LIBFUZZER)
    cmake_pop_check_state()
    if(NOT MARS_TITAN_HAS_LIBFUZZER)
        message(FATAL_ERROR "El compilador no puede enlazar libFuzzer con los sanitizadores")
    endif()
endif()

function(mars_titan_instrument_target target)
    if(NOT MARS_TITAN_SANITIZER STREQUAL "none")
        target_compile_options(${target} PRIVATE ${MARS_TITAN_SANITIZER_FLAGS})
        target_link_options(${target} PUBLIC ${MARS_TITAN_SANITIZER_FLAGS})
        if(MSVC)
            target_compile_options(${target} PRIVATE /Zi)
            target_link_options(${target} PRIVATE /DEBUG /INCREMENTAL:NO)
        else()
            target_compile_options(${target} PRIVATE -g -fno-omit-frame-pointer
                -fno-optimize-sibling-calls -fno-sanitize-recover=all)
            if(MARS_TITAN_SANITIZER STREQUAL "memory")
                target_compile_options(${target} PRIVATE -fsanitize-memory-track-origins=2
                    "$<$<COMPILE_LANGUAGE:CXX>:-nostdinc++;-isystem${MARS_TITAN_MSAN_STDLIB_ROOT}/include/c++/v1>")
                target_link_options(${target} PUBLIC "$<$<LINK_LANGUAGE:CXX>:-stdlib=libc++>"
                    "-L${MARS_TITAN_MSAN_STDLIB_ROOT}/lib" "-Wl,-rpath,${MARS_TITAN_MSAN_STDLIB_ROOT}/lib")
                target_link_libraries(${target} PRIVATE "${MARS_TITAN_MSAN_c__abi}")
                get_target_property(target_type ${target} TYPE)
                if(target_type STREQUAL "EXECUTABLE")
                    target_compile_options(${target} PRIVATE -fPIE)
                    target_link_options(${target} PRIVATE -pie)
                endif()
            endif()
        endif()
    elseif(MARS_TITAN_PROFILE AND NOT MSVC)
        target_compile_options(${target} PRIVATE -fno-omit-frame-pointer -g)
    endif()
    if(MARS_TITAN_ENABLE_IPO)
        set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
    endif()
    if(NOT MARS_TITAN_PGO STREQUAL "off")
        if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            message(FATAL_ERROR "El perfil PGO explícito requiere GCC o Clang")
        endif()
        if(MARS_TITAN_PGO STREQUAL "use" AND NOT EXISTS "${MARS_TITAN_PGO_DATA}")
            message(FATAL_ERROR "No existe el perfil PGO solicitado")
        endif()
        if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            set(pgo_flag "-fprofile-${MARS_TITAN_PGO}=${MARS_TITAN_PGO_DATA}")
        elseif(MARS_TITAN_PGO STREQUAL "generate")
            file(MAKE_DIRECTORY "${MARS_TITAN_PGO_DATA}")
            set(pgo_flag "-fprofile-instr-generate=${MARS_TITAN_PGO_DATA}/%m-%p.profraw")
        else()
            if(IS_DIRECTORY "${MARS_TITAN_PGO_DATA}")
                message(FATAL_ERROR "Clang necesita un archivo .profdata combinado con llvm-profdata")
            endif()
            set(pgo_flag "-fprofile-instr-use=${MARS_TITAN_PGO_DATA}")
        endif()
        target_compile_options(${target} PRIVATE "${pgo_flag}")
        target_link_options(${target} PUBLIC "${pgo_flag}")
    endif()
endfunction()

find_program(MARS_TITAN_SYMBOLIZER NAMES llvm-symbolizer-21 llvm-symbolizer)
function(mars_titan_sanitizer_test_environment)
    set(environment "DEBUGINFOD_URLS=")
    if(MARS_TITAN_ENABLE_COVERAGE)
        list(APPEND environment "LLVM_PROFILE_FILE=${MARS_TITAN_COVERAGE_DIR}/%m-%p.profraw")
    endif()
    if(MARS_TITAN_SANITIZER MATCHES "^address")
        set(asan_options "halt_on_error=1:symbolize=1")
        if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            string(APPEND asan_options ":detect_leaks=1")
        endif()
        list(APPEND environment "ASAN_OPTIONS=${asan_options}" "UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1")
        if(MARS_TITAN_SYMBOLIZER)
            list(APPEND environment "ASAN_SYMBOLIZER_PATH=${MARS_TITAN_SYMBOLIZER}")
        endif()
    elseif(MARS_TITAN_SANITIZER STREQUAL "thread")
        list(APPEND environment "TSAN_OPTIONS=halt_on_error=1")
    elseif(MARS_TITAN_SANITIZER STREQUAL "memory")
        list(APPEND environment "MSAN_OPTIONS=halt_on_error=1:print_stats=1")
    endif()
    set_tests_properties(${ARGN} PROPERTIES ENVIRONMENT "${environment}")
endfunction()
