option(MARS_TITAN_BUILD_LEARNING_CONTROLS "Compilar los controles técnicos de replay y adaptación" OFF)
if(NOT MARS_TITAN_BUILD_LEARNING_CONTROLS)
    return()
endif()

include(CTest)
add_library(mars_titan_replay_schedule STATIC src/replay_schedule.cpp)
target_include_directories(mars_titan_replay_schedule PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
mars_titan_configure_target(mars_titan_replay_schedule)
add_executable(mars-titan-replay-control src/replay_control_main.cpp)
target_link_libraries(mars-titan-replay-control PRIVATE mars_titan_replay_schedule)
mars_titan_configure_target(mars-titan-replay-control)
if(BUILD_TESTING)
    add_executable(replay_schedule_tests tests/replay_schedule_tests.cpp)
    target_link_libraries(replay_schedule_tests PRIVATE mars_titan_replay_schedule)
    mars_titan_configure_target(replay_schedule_tests)
    add_test(NAME replay_schedule COMMAND replay_schedule_tests)
    set_tests_properties(replay_schedule PROPERTIES TIMEOUT 60 LABELS "unit;integration;controls")
    mars_titan_sanitizer_test_environment(replay_schedule)
    add_test(NAME replay_control COMMAND mars-titan-replay-control 17 3 4 71 3)
    add_test(NAME replay_control_invalid COMMAND mars-titan-replay-control 0)
    set_tests_properties(replay_control_invalid PROPERTIES WILL_FAIL TRUE)
    set_tests_properties(replay_control replay_control_invalid PROPERTIES TIMEOUT 60 LABELS "integration;controls")
    mars_titan_sanitizer_test_environment(replay_control replay_control_invalid)
endif()

if(MARS_TITAN_BUILD_FUZZER)
    add_executable(fuzz_replay_schedule tests/fuzz_replay_schedule.cpp)
    target_link_libraries(fuzz_replay_schedule PRIVATE mars_titan_replay_schedule)
    mars_titan_configure_target(fuzz_replay_schedule)
    target_compile_options(mars_titan_replay_schedule PRIVATE -fsanitize=fuzzer-no-link)
    target_compile_options(fuzz_replay_schedule PRIVATE -fsanitize=fuzzer-no-link)
    target_link_options(fuzz_replay_schedule PRIVATE -fsanitize=fuzzer)
    if(BUILD_TESTING)
        add_test(NAME fuzz_replay_schedule_smoke COMMAND fuzz_replay_schedule
            -seed=71 -runs=1000 -max_len=4096 -timeout=5 -rss_limit_mb=1024)
        set_tests_properties(fuzz_replay_schedule_smoke PROPERTIES TIMEOUT 60 LABELS "fuzz;controls")
        mars_titan_sanitizer_test_environment(fuzz_replay_schedule_smoke)
    endif()
endif()

if(MARS_TITAN_ENABLE_STATIC_ANALYZER AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    add_custom_target(learning-controls-analysis
        COMMAND "${MARS_TITAN_CLANG_CHECK}" --analyze "-p=${CMAKE_BINARY_DIR}"
            --extra-arg=-Xanalyzer --extra-arg=-analyzer-werror
            "${CMAKE_CURRENT_SOURCE_DIR}/src/replay_schedule.cpp"
            "${CMAKE_CURRENT_SOURCE_DIR}/src/replay_control_main.cpp"
        VERBATIM)
endif()

option(MARS_TITAN_BUILD_ADAPTER_CONTROLS "Compilar el control matricial con LibTorch" OFF)
option(MARS_TITAN_TEST_ADAPTER_CUDA "Registrar las pruebas CUDA para una ventana GPU exclusiva" OFF)
if(MARS_TITAN_BUILD_ADAPTER_CONTROLS)
    if(MARS_TITAN_SANITIZER STREQUAL "thread" OR MARS_TITAN_SANITIZER STREQUAL "memory")
        message(FATAL_ERROR "El control de adaptadores necesita LibTorch instrumentado para TSan o MSan")
    endif()
    include(cmake/TorchDependencies.cmake)
    mars_titan_find_torch()
    if(MARS_TITAN_TEST_ADAPTER_CUDA AND NOT MARS_TITAN_TORCH_HAS_CUDA)
        message(FATAL_ERROR "Las pruebas CUDA del adaptador requieren el backend LibTorch CUDA")
    endif()
    add_library(mars_titan_adapter_control STATIC src/adapter_control.cpp)
    target_include_directories(mars_titan_adapter_control PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(mars_titan_adapter_control PUBLIC mars_titan::torch)
    mars_titan_configure_target(mars_titan_adapter_control)
    add_executable(mars-titan-adapter-control src/adapter_control_main.cpp)
    target_link_libraries(mars-titan-adapter-control PRIVATE mars_titan_adapter_control)
    mars_titan_configure_target(mars-titan-adapter-control)
    if(BUILD_TESTING)
        add_executable(adapter_control_tests tests/adapter_control_tests.cpp)
        target_link_libraries(adapter_control_tests PRIVATE mars_titan_adapter_control)
        mars_titan_configure_target(adapter_control_tests)
        add_test(NAME adapter_control COMMAND adapter_control_tests cpu)
        set_tests_properties(adapter_control PROPERTIES TIMEOUT 120 LABELS "unit;integration;controls")
        mars_titan_sanitizer_test_environment(adapter_control)
        set_property(TEST adapter_control APPEND PROPERTY ENVIRONMENT
            "CUDA_VISIBLE_DEVICES=-1" "OMP_NUM_THREADS=1" "MKL_NUM_THREADS=1")
        add_test(NAME adapter_control_cli COMMAND mars-titan-adapter-control cpu 8 4 3 2 4 2)
        add_test(NAME adapter_control_cli_invalid COMMAND mars-titan-adapter-control cuda:1)
        set_tests_properties(adapter_control_cli_invalid PROPERTIES WILL_FAIL TRUE)
        set_tests_properties(adapter_control_cli adapter_control_cli_invalid PROPERTIES
            TIMEOUT 120 LABELS "integration;controls")
        mars_titan_sanitizer_test_environment(adapter_control_cli adapter_control_cli_invalid)
        set_property(TEST adapter_control_cli adapter_control_cli_invalid APPEND PROPERTY ENVIRONMENT
            "CUDA_VISIBLE_DEVICES=-1" "OMP_NUM_THREADS=1" "MKL_NUM_THREADS=1")
        if(MARS_TITAN_TEST_ADAPTER_CUDA)
            add_test(NAME adapter_control_cuda COMMAND adapter_control_tests cuda:0)
            add_test(NAME adapter_control_cli_cuda COMMAND mars-titan-adapter-control cuda:0 8 4 3 2 4 2)
            set_tests_properties(adapter_control_cuda adapter_control_cli_cuda PROPERTIES
                TIMEOUT 120 LABELS "integration;controls;cuda" RUN_SERIAL TRUE)
            mars_titan_sanitizer_test_environment(adapter_control_cuda adapter_control_cli_cuda)
            set_property(TEST adapter_control_cuda adapter_control_cli_cuda APPEND PROPERTY ENVIRONMENT
                "OMP_NUM_THREADS=1" "MKL_NUM_THREADS=1")
        endif()
    endif()
    if(MARS_TITAN_ENABLE_STATIC_ANALYZER AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        add_custom_target(adapter-controls-analysis
            COMMAND "${MARS_TITAN_CLANG_CHECK}" --analyze "-p=${CMAKE_BINARY_DIR}"
                --extra-arg=-Xanalyzer --extra-arg=-analyzer-werror
                "${CMAKE_CURRENT_SOURCE_DIR}/src/adapter_control.cpp"
                "${CMAKE_CURRENT_SOURCE_DIR}/src/adapter_control_main.cpp"
            VERBATIM)
    endif()
    if(MARS_TITAN_BUILD_FUZZER)
        add_executable(fuzz_adapter_control tests/fuzz_adapter_control.cpp)
        target_link_libraries(fuzz_adapter_control PRIVATE mars_titan_adapter_control)
        mars_titan_configure_target(fuzz_adapter_control)
        target_compile_options(mars_titan_adapter_control PRIVATE -fsanitize=fuzzer-no-link)
        target_compile_options(fuzz_adapter_control PRIVATE -fsanitize=fuzzer-no-link)
        target_link_options(fuzz_adapter_control PRIVATE -fsanitize=fuzzer)
        if(BUILD_TESTING)
            add_test(NAME fuzz_adapter_control_smoke COMMAND fuzz_adapter_control
                -seed=71 -runs=1000 -max_len=4096 -timeout=5 -rss_limit_mb=2048)
            set_tests_properties(fuzz_adapter_control_smoke PROPERTIES TIMEOUT 120 LABELS "fuzz;controls")
            mars_titan_sanitizer_test_environment(fuzz_adapter_control_smoke)
            set_property(TEST fuzz_adapter_control_smoke APPEND PROPERTY ENVIRONMENT
                "CUDA_VISIBLE_DEVICES=-1" "OMP_NUM_THREADS=1" "MKL_NUM_THREADS=1")
        endif()
    endif()
endif()
