# Lectura nativa de la protección local del aprendizaje, compartida por PPO y los controles.
set(MARS_TITAN_BLOCKED_HOLD "${CMAKE_CURRENT_BINARY_DIR}/learning-hold-blocked.json")
if(TARGET mars_titan_learning_hold)
    return()
endif()
if(NOT TARGET nlohmann_json::nlohmann_json)
    include("${CMAKE_CURRENT_LIST_DIR}/RunnerDependencies.cmake")
    mars_titan_find_json()
endif()
add_library(mars_titan_learning_hold STATIC src/learning_hold.cpp)
target_include_directories(mars_titan_learning_hold PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(mars_titan_learning_hold PRIVATE nlohmann_json::nlohmann_json)
mars_titan_configure_target(mars_titan_learning_hold)
if(BUILD_TESTING)
    file(WRITE "${MARS_TITAN_BLOCKED_HOLD}" "{\"training_allowed\": false}\n")
    add_executable(learning_hold_tests tests/learning_hold_tests.cpp)
    target_link_libraries(learning_hold_tests PRIVATE mars_titan_learning_hold)
    mars_titan_configure_target(learning_hold_tests)
    add_test(NAME learning_hold COMMAND learning_hold_tests)
    set_tests_properties(learning_hold PROPERTIES TIMEOUT 60 LABELS "unit;learning-hold")
    mars_titan_sanitizer_test_environment(learning_hold)
endif()
