file(GLOB profiles "${PROFILE_DIR}/*.profraw")
if(NOT profiles)
    message(FATAL_ERROR "No hay perfiles. Ejecuta primero las pruebas de la compilación instrumentada")
endif()
set(newest_binary 0)
foreach(object IN LISTS OBJECTS)
    file(TIMESTAMP "${object}" modified "%s" UTC)
    if(modified GREATER newest_binary)
        set(newest_binary "${modified}")
    endif()
endforeach()
foreach(profile IN LISTS profiles)
    file(TIMESTAMP "${profile}" modified "%s" UTC)
    if(modified LESS newest_binary)
        message(FATAL_ERROR "Hay perfiles anteriores a los binarios. Usa un directorio limpio de cobertura y repite las pruebas")
    endif()
endforeach()
execute_process(COMMAND "${PROFDATA}" merge -sparse ${profiles} -o "${PROFILE_DIR}/native.profdata"
    RESULT_VARIABLE result ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "No se pudo combinar la cobertura: ${errors}")
endif()
list(POP_FRONT OBJECTS primary)
set(extra_objects "")
foreach(object IN LISTS OBJECTS)
    list(APPEND extra_objects -object "${object}")
endforeach()
set(options "${primary}" ${extra_objects} "-instr-profile=${PROFILE_DIR}/native.profdata"
    "-ignore-filename-regex=(/usr/|_deps/|[.]venv/|native/tests/)"
    "-compilation-dir=${SOURCE_ROOT}")
execute_process(COMMAND "${COV}" report ${options} -show-branch-summary
    WORKING_DIRECTORY "${SOURCE_ROOT}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "llvm-cov no pudo generar el resumen de cobertura")
endif()
execute_process(COMMAND "${COV}" export ${options}
    WORKING_DIRECTORY "${SOURCE_ROOT}" OUTPUT_FILE "${PROFILE_DIR}/native-coverage.json"
    ERROR_VARIABLE errors RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "llvm-cov no pudo exportar la cobertura: ${errors}")
endif()
