include(CheckCXXSourceCompiles)
include(CMakePushCheckState)

option(MARS_TITAN_LIBTORCH_ENABLE_CUDA "Enlazar el backend CUDA del SDK LibTorch existente" ON)
set(MARS_TITAN_TORCH_ENVIRONMENT "" CACHE PATH "Entorno uv existente del SDK LibTorch, vacío para usar .venv")

function(mars_titan_find_torch)
    if(TARGET mars_titan::torch)
        return()
    endif()
    if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
        message(FATAL_ERROR "La integración con el SDK LibTorch del entorno uv requiere Linux")
    endif()
    find_program(MARS_TITAN_UV NAMES uv REQUIRED)
    get_filename_component(project_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../.." ABSOLUTE)
    set(sdk_environment "${MARS_TITAN_TORCH_ENVIRONMENT}")
    if(NOT sdk_environment)
        set(sdk_environment "${project_root}/.venv")
    endif()
    if(NOT EXISTS "${sdk_environment}/pyvenv.cfg")
        message(FATAL_ERROR "Falta el entorno local de uv con PyTorch. Prepare sus dependencias antes de configurar LibTorch")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "UV_PROJECT_ENVIRONMENT=${sdk_environment}"
        "${MARS_TITAN_UV}" run --no-sync --project "${project_root}" python -c
        "import json,pathlib,torch; root=pathlib.Path(torch.__file__).parent; cuda=torch.version.cuda or ''; candidates=[root.parent/'nvidia'/('cu'+cuda.split('.')[0])/'include',root.parent/'nvidia'/'cuda_runtime'/'include']; runtime=next((str(p) for p in candidates if (p/'cuda_runtime_api.h').is_file()),''); print(json.dumps(dict(root=str(root),version=torch.__version__,cuda_version=cuda,cxx11_abi=int(torch.compiled_with_cxx11_abi()),cpu_capability=torch.backends.cpu.get_cpu_capability(),config=torch.__config__.show(),cuda_include=runtime)))"
        WORKING_DIRECTORY "${project_root}"
        RESULT_VARIABLE probe_result OUTPUT_VARIABLE sdk ERROR_VARIABLE probe_error
        OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 30)
    if(NOT probe_result EQUAL 0)
        message(FATAL_ERROR "No se pudo consultar el SDK LibTorch del entorno uv existente: ${probe_error}")
    endif()
    foreach(key root version cuda_version cxx11_abi cpu_capability config cuda_include)
        string(JSON sdk_${key} ERROR_VARIABLE json_error GET "${sdk}" ${key})
        if(json_error)
            message(FATAL_ERROR "No se pudo interpretar el SDK LibTorch: ${json_error}")
        endif()
    endforeach()
    string(REGEX MATCH "^[0-9]+\\.[0-9]+\\.[0-9]+" sdk_release "${sdk_version}")
    if(NOT sdk_release OR sdk_release VERSION_LESS "2.14.0" OR NOT sdk_release VERSION_LESS "3.0.0")
        message(FATAL_ERROR "El aprendizaje nativo necesita PyTorch >=2.14,<3. Versión instalada: ${sdk_version}")
    endif()
    if(NOT sdk_cxx11_abi MATCHES "^[01]$")
        message(FATAL_ERROR "El SDK LibTorch no declara una ABI libstdc++ reconocida")
    endif()
    cmake_push_check_state(RESET)
    unset(MARS_TITAN_TORCH_ABI_COMPATIBLE CACHE)
    check_cxx_source_compiles(
        "#include <string>\n#if !defined(__GLIBCXX__) || !defined(_GLIBCXX_USE_CXX11_ABI) || _GLIBCXX_USE_CXX11_ABI != ${sdk_cxx11_abi}\n#error ABI incompatible con LibTorch\n#endif\nint main() { return 0; }"
        MARS_TITAN_TORCH_ABI_COMPATIBLE)
    cmake_pop_check_state()
    if(NOT MARS_TITAN_TORCH_ABI_COMPATIBLE)
        message(FATAL_ERROR "La ABI de libstdc++ del compilador no coincide con LibTorch (${sdk_cxx11_abi}). No se alterará la ABI del proyecto")
    endif()

    set(sdk_includes "${sdk_root}/include" "${sdk_root}/include/torch/csrc/api/include")
    if(NOT EXISTS "${sdk_root}/include/ATen/ATen.h" OR
       NOT EXISTS "${sdk_root}/include/torch/csrc/api/include/torch/nn.h")
        message(FATAL_ERROR "El paquete PyTorch no incluye las cabeceras del frontend C++")
    endif()
    set(sdk_components c10 torch_cpu)
    set(sdk_has_cuda OFF)
    if(MARS_TITAN_LIBTORCH_ENABLE_CUDA AND sdk_cuda_version)
        if(NOT sdk_cuda_include)
            message(FATAL_ERROR "El SDK CUDA de PyTorch no incluye cuda_runtime_api.h")
        endif()
        list(APPEND sdk_includes "${sdk_cuda_include}")
        list(APPEND sdk_components c10_cuda torch_cuda)
        set(sdk_has_cuda ON)
    endif()
    foreach(component IN LISTS sdk_components)
        set(component_path "${sdk_root}/lib/lib${component}.so")
        if(NOT EXISTS "${component_path}")
            message(FATAL_ERROR "Falta una biblioteca del SDK LibTorch: ${component_path}")
        endif()
        add_library(mars_titan_torch_${component} SHARED IMPORTED)
        set_target_properties(mars_titan_torch_${component} PROPERTIES IMPORTED_LOCATION "${component_path}")
    endforeach()
    add_library(mars_titan_torch INTERFACE)
    add_library(mars_titan::torch ALIAS mars_titan_torch)
    target_compile_features(mars_titan_torch INTERFACE cxx_std_20)
    target_include_directories(mars_titan_torch SYSTEM INTERFACE ${sdk_includes})
    target_link_libraries(mars_titan_torch INTERFACE mars_titan_torch_torch_cpu mars_titan_torch_c10)
    if(sdk_has_cuda)
        # La biblioteca registra sus kernels al cargarse, aunque no se llame a un símbolo CUDA.
        target_link_libraries(mars_titan_torch INTERFACE
            "-Wl,--push-state,--no-as-needed" mars_titan_torch_torch_cuda "-Wl,--pop-state"
            mars_titan_torch_c10_cuda)
        target_compile_definitions(mars_titan_torch INTERFACE MARS_TITAN_LIBTORCH_CUDA=1)
        if(NOT EXISTS "${sdk_cuda_include}/crt/host_config.h")
            message(STATUS "El runtime CUDA del wheel no incluye CRT. Use las API genéricas ATen para dispositivo, RNG y configuración de memoria")
        endif()
    endif()
    foreach(key root version cuda_version cxx11_abi cpu_capability config)
        string(TOUPPER "${key}" metadata_key)
        set(MARS_TITAN_TORCH_${metadata_key} "${sdk_${key}}" PARENT_SCOPE)
        set_property(TARGET mars_titan_torch PROPERTY MARS_TITAN_TORCH_${metadata_key} "${sdk_${key}}")
    endforeach()
    set(MARS_TITAN_TORCH_HAS_CUDA "${sdk_has_cuda}" PARENT_SCOPE)
    set_property(TARGET mars_titan_torch PROPERTY MARS_TITAN_TORCH_HAS_CUDA "${sdk_has_cuda}")
    message(STATUS "LibTorch ${sdk_version}, ABI ${sdk_cxx11_abi}, CPU ${sdk_cpu_capability}, backend CUDA ${sdk_has_cuda}. SDK del entorno uv, sin compilación CUDA")
endfunction()
